### PR TITLE
Feature/add restaurant

### PR DESCRIPTION
**Pull request by JailsonJr-BR**
## Add new restaurant endpoint

This PR adds a new endpoint to the API to create a new restaurant. The endpoint is located at `/restaurant` and it accepts a JSON body with the following properties:

- name: The name of the restaurant.
- category: The category of the restaurant.
- address: The address of the restaurant.
 
## Changes

The following changes have been made to the code:

- A new endpoint has been added to the `restaurantRouter.js` file.
- The `restaurantController.js` file has been updated to handle the new endpoint.
- The `restaurantService.js` file has been updated to handle the business rules.
 
## Screenshots (if appropriate)

| Create restaurant endpoint | 
| ------ |
| image |

|Get restaurants endpoint |
| ------ |
| image |

### CODE REVIEW

**Comment by denise-techlead** [comment]
Maravilha! Aguarde um momento enquanto reviso seu código. 👀

**Comment by denise-techlead** [comment]
Verifiquei que os testes unitários não passaram. Isso significa que há algo de errado com sua solução. Submeta um novo commit com a correção neste branch para atualizar o Pull Request. 👀

**Comment by denise-techlead** [comment]
Verifiquei que os testes unitários não passaram. Isso significa que há algo de errado com sua solução. Submeta um novo commit com a correção neste branch para atualizar o Pull Request. 👀

**Comment by JailsonJr-BR** [comment]
> ## Add new restaurant endpoint
> This PR adds a new endpoint to the API to create a new restaurant. The endpoint is located at `/restaurant` and it accepts a JSON body with the following properties:
> 
> * name: The name of the restaurant.
> * category: The category of the restaurant.
> * address: The address of the restaurant.
> 
> ## Changes
> The following changes have been made to the code:
> 
> * A new endpoint has been added to the `restaurantRouter.js` file.
> * The `restaurantController.js` file has been updated to handle the new endpoint.
> * The `restaurantService.js` file has been updated to handle the business rules.
> 
> ## Screenshots (if appropriate)
> Create restaurant endpoint
> image
> Get restaurants endpoint
> image

**Pull request closed without merging**
